### ISSUE TITLE
berechnung GesamtAktuellInfizierteBerechnet

### ISSUE THREAD

**Issue by uwesterr** [uwesterr/CoronaPredict#105]
momentan wird im master branch GesamtAktuellInfizierteBerechnet wie folgt berechnet

   ```r
 if (nrow(calcDf) < ende_inf){
      NeuGesamtInfizierteBerechnetHistory = updatecalcDf$RestanteilStartwert*faktor_n_inf
    } else {
      NeuGesamtInfizierteBerechnetHistory = 0
    } 
    
    # TG: Ansatz die gesamt neu infizierten aus den GesamtAktuellInfizierten zu berechnen. Siehe hierzu auch geaenderte Funktion 
    
    # browser()  
    updatecalcDf$GesamtAktuellInfizierteBerechnet <-  NeuGesamtInfizierteBerechnetHistory +
      rollapply(calcDf$NeuGesamtInfizierteBerechnet, ende_inf, sum,
                align = "right", partial =TRUE) %>% tail(1)
```

aber eigentlich müsste ein window (tag-ti bis tag-(ti+ta)) über die NeuGesamtInfizierteBerechnet geschoben werden

im branch https://github.com/uwesterr/CoronaPredict/tree/bechnung_von_GesamtAktuellInfizierteBerechnet ist das implementiert  commit https://github.com/uwesterr/CoronaPredict/commit/ad10020c4480b93b2cf547871f013434189ebc6e 
  ```r
  updatecalcDf$GesamtAktuellInfizierteBerechnet <- calcDf %>% filter((Tag <= updatecalcDf$Tag - ti) & (Tag > updatecalcDf$Tag - ende_inf )) %>% 
      summarise(sum = sum(NeuGesamtInfizierteBerechnet)) %>% as.numeric()
```

damit dies auch am begin der loop funktioniert wenn noch keine daten der Vergangenheit vorhanden sind werden diese daten der Vergangenheit erzeugt
```r
  # find day on which the first was case would have been reported with given Rt 
  offsetDay <- ceiling(log(n0_erfasst*faktor_n_inf,Rt)) # calculate the day when one case was there 
  calcInit <- data.frame(Tag = seq(startDate- offsetDay, startDate, by = 1))  %>% 
    mutate(indexBack = as.numeric(-(Tag - startDate)),
           TaeglichReproduktionsRateRt       = Rt,
#           RestanteilStartwert               = NA,
           NeuInfizierteBerechnet            = NA,
           GesamtInfizierteBerechnet         = 0,
           GesamtAktuellInfizierteBerechnet  = 0,
           NeuGesamtInfizierteBerechnet      = NA,
           KhBerechnet                       = NA,
           IntensivBerechnet                 = 0,
           NeueToteBerechnet                 = 0,
           ToteBerechnet                     = 0,
           ReduktionAbDatum                  = 0,
           ReduzierteRt                      = 0,
           MaxKhBerechnet                    = 0,
           MaxIntBerechnet                   = 0)
 
  for (i in 1:nrow(calcInit)) {
    calcInit$ReduzierteRt[i] =  calcReduzierung(calcInit[i,], reduzierung_datum1, reduzierung_rt1, reduzierung_datum2, reduzierung_rt2, reduzierung_datum3, reduzierung_rt3, ta)
    
  }
  
  calcInit$ReduzierteRt <- calcReduzierung(calcInit, reduzierung_datum1, reduzierung_rt1, reduzierung_datum2, reduzierung_rt2, reduzierung_datum3, reduzierung_rt3, ta)
  calcInit <- calcInit %>% mutate(GesamtInfizierteBerechnet = n0_erfasst*faktor_n_inf/ReduzierteRt^indexBack,
                      ErfassteInfizierteBerechnet = GesamtInfizierteBerechnet / faktor_n_inf,
                      GesamtAktuellInfizierteBerechnet = rollapply(GesamtInfizierteBerechnet, ende_inf, sum,align = "right", fill = NA, partial =TRUE) -
                        rollapply(GesamtInfizierteBerechnet, start_inf, sum,align = "right", fill = NA, partial =TRUE),
                       NeuGesamtInfizierteBerechnet = (ReduzierteRt-1)*GesamtAktuellInfizierteBerechnet,
                      NeuInfizierteBerechnet = NeuGesamtInfizierteBerechnet/faktor_n_inf)
```

das Ergebnis sieht mit entsprechenden Einstellungen so aus:
![GesamtAktuellInfizierteBerechnetResult](https://user-images.githubusercontent.com/20616185/78571830-f869e000-7826-11ea-8f45-71d7fd35b841.png)

**Comment by thomasgneiting** [comment]
Sieht vernünftig aus. Erfordert aber geänderte Anpassung der Parameter.

**Comment by Fabian79FFM** [comment]
Hallo Uwe, 
ich muss zugeben, dass ich eigentlich gedacht hätte, dass 
GesamtAktuellInfizierteBerechnet = Dunkelziffer Infizierte * AktuellInfizierteBerechnet. 
Im aktuellen Masterbranch schwankt aber der Quotient aus GesamtAktuell... und AktuellInf... zwisch 15 un 17,xx. Habe ich da einen Denkfehler, oder warum implementiert man das nicht mit der Formel oben? Insgesamt ist ja m.E. noch ziemlich unklar, wie hoch die Dunkelziffer denn ist...
Viele Grüße
Fabian

**Comment by Fabian79FFM** [comment]
Ich habe nochmal den Quotienten aus GesamtAktuellInfiziertBerechnet und AktuellInfiziertBerechnet in Deinem neuen Code/branch gebildet. Das sieht für Deutschland so aus (test habe ich diesen Quotienten genannt):
![Rplot](https://user-images.githubusercontent.com/62776846/78607851-23bcf100-7860-11ea-993f-8e2891465395.png)
Für mich nicht ganz intuitiv...

**Comment by thomasgneiting** [comment]
Die Anpassung erfolgt über einen Optimierer z.B. in https://github.com/uwesterr/CoronaPredict/commit/f9f2e0271f24ab37b9c334ef97eb40cd036dd3a9

**Comment by uwesterr** [comment]
> Ich habe nochmal den Quotienten aus GesamtAktuellInfiziertBerechnet und AktuellInfiziertBerechnet in Deinem neuen Code/branch gebildet. Das sieht für Deutschland so aus (test habe ich diesen Quotienten genannt):
> ![Rplot](https://user-images.githubusercontent.com/62776846/78607851-23bcf100-7860-11ea-993f-8e2891465395.png)
> Für mich nicht ganz intuitiv...

danke für den Hinweis, war noch ein bug

```r
  calcDf <- calcDf %>% mutate(AktuellInfizierteBerechnet = ifelse(ID==1,n0_erfasst,
                                                                  rollapply(NeuInfizierteBerechnet, ende_inf, sum,align = "right", fill = NA, partial =TRUE) -NeuInfizierteBerechnet))
```
muss jetzt sein

`  calcDf <- calcDf %>% mutate(AktuellInfizierteBerechnet = GesamtAktuellInfizierteBerechnet/faktor_n_inf)`

jetzt sieht dein plot so aus wie er aussehen soll

![GesamtDividedByAktuell](https://user-images.githubusercontent.com/20616185/78640359-e6804f80-78af-11ea-9602-f204df501b52.png)

**Comment by thomasgneiting** [comment]
Berechnung ist ok
