### ISSUE TITLE
Tool tips formatieren

### ISSUE THREAD

**Issue by uwesterr** [uwesterr/CoronaPredict#22]
Die tooltips bei den ggplotly plots
- sollten gerundet werden
- sollten übersichtlicher werden

**Comment by thomasgneiting** [comment]
Hallo Fabian, 
mir ist noch aufgefallen, das bei den Tooltips in den Diagrammen mit 2 Kurven 
![grafik](https://user-images.githubusercontent.com/62795691/77856783-c68ac500-71f9-11ea-987e-cad73bb272f1.png) 
im grünen Tooltip auch "kHberechnet" erscheint und die Zahl dahinter die Anzahl der Intensivbetten angibt.

**Comment by uwesterr** [comment]
solved in commit 1476e395bdb1514f298845520e694593bd1d1358
