### ISSUE TITLE
Einfügen Confidenzintervall (CI) mit z.B. 90% Abdeckung

### ISSUE THREAD

**Issue by thomasgneiting** [uwesterr/CoronaPredict#32]
Input von Matthias Havemann um zu zeigen, wie groß die Bandbreite der Vorhersage ist. 
Fabian: Bei mir ist es 35 Jahre her dass ich so was in der 12. Klasse Gymnasium gemacht habe. 
- Aus was kann man das sinnvollerweise berechnen? 
- Anzahl der Samples
- Varianz der Angaben (Infektiosität?, Prozentsatz Krankenhaus, ...)
- ...?

**Comment by uwesterr** [comment]
R0 und n0 nom min und max Berechnung wie folgt
```r
startDate <-  as.Date('2020-03-01')
  calcR0ConN0Conf <- function(lmModel, startDate) {
    n0_erfasst_conf <- lmModel %>% predict(data.frame(MeldeDate =startDate), interval = "confidence", level = 0.95)
    n0_erfasst_nom_min_max <- 10^n0_erfasst_conf
    R0_nom <- 10^lmModel[["coefficients"]][["MeldeDate"]]
    R0_min_max <- 10^confint(lmModel, level = .95)
    R0_conf_nom_min_max <- c(R0_nom, R0_min_max[[2]], R0_min_max[[4]] )
    return(list(n0_erfasst_nom_min_max, R0_conf_nom_min_max))
  }
```

danach Rechenkern mit 

- min werten
- nom werten
- max werten

durchführen

**Comment by uwesterr** [comment]
aufruf Rechenkern

```r
 n0_erfasst <- 	r0_no_erfasstDf$n0_erfasst %>% unique()
Rt <- r0_no_erfasstDf$R0
```

**Comment by uwesterr** [comment]
mit commit https://github.com/uwesterr/CoronaPredict/commit/9b6463523178bd0e1f88a0614c5752a724bf32cc hat fabian eine andere CI Methode implementiert

**Comment by uwesterr** [comment]
kumulierte werte müssen noch implementiert werden

**Comment by m-hav** [comment]
Hier ist noch ein Bug mit der Berechnung der CIs (ich hab es leider immer noch nicht geschafft eure Formel zu prüfen, sorry...):
![image](https://user-images.githubusercontent.com/11753483/79206768-1e533e00-7e40-11ea-8cde-8151da210eae.png)

Konfiguration für diesen Bug:
https://covid19.admos.de/shiny/myNewApp/?_state_id_=564b9160bbb3fe1e

**Comment by m-hav** [comment]
Ähnlich hier für Gießen mit Standardeinstellungen:
![image](https://user-images.githubusercontent.com/11753483/79208094-e8af5480-7e41-11ea-89d5-09cfcc30a814.png)

Die realen Zahlen sind im Moment mindestens 400% höher als in diesem Modell...

**Comment by uwesterr** [comment]
die Berechnung der Krankenhaus wird erst dann aussagefähig wenn wir reale Daten zum modellieren haben, auf den input warten wir noch...
