### ISSUE TITLE
Doku erstellen

### ISSUE THREAD

**Issue by thomasgneiting** [uwesterr/CoronaPredict#35]
Anleitung, wie Kurve angepasst werden muss. 

Was, wenn der Startwert nicht stimmt?
Startdatum anpassen !!
Evtl. erste Massnahme nach hinten schieben
Beispiel: Landkreis Siegen Wittgenstein oder Böblingen !

**Comment by uwesterr** [comment]
umwandeln von docx in markdown in terminal

`pandoc -o Anleitung.md --extract-media=./ CoPE_200330.docx`
