### ISSUE TITLE
Kurven für Todesfälle mit aufnehmen

### ISSUE THREAD

**Issue by thomasgneiting** [uwesterr/CoronaPredict#36]
Kurven für Todesfälle mit aufnehmen und Daten von RKI mit anzeigen. 

![grafik](https://user-images.githubusercontent.com/62795691/77859053-7c104500-7207-11ea-9093-45c39058aa30.png)

Dabei "Todesfälle" verwenden, nicht so hart wie "Tote"

**Comment by uwesterr** [comment]
added 
sumToteBund = cumsum(AnzahlTodesfall),
sumToteBundesland = cumsum(AnzahlTodesfall)

**Comment by uwesterr** [comment]
kurven sind drin, aber tooltips zeigen werte nicht
