### ISSUE TITLE
Berechnung von R0 durch Optimierung

### ISSUE THREAD

**Issue by thomasgneiting** [uwesterr/CoronaPredict#99]
Fabian hatte in seiner email vom 26.3. bereits diesen Punkt erwähnt: 

Wieso rechnen wir (wenn ich das richtig gesehen habe) zur Berechnung der Neuinfektionen die "ReduzierteRt" auf die kumulierten Infizierten ("GesamtInfizierteBerechnet"), nicht auf die Ansteckenden ("AktuellInfizierteBerechnet"). Das ist für mich nicht so intuitiv. Ich verstehe, dass durch die exponentielle Absenkung von "ReduzierteRt" die Neuinfektionen später dennoch sinken. Aber insbesondere bevor die Reduktionsmaßnahmen wirken ("WirksamkeitReduktion=0") kann ich die Formel nicht nachvollziehen.

Das ist auch aus meiner Sicht absolut ok, da nur die "GesamtAktuellInfizierten" auch wieder neue Gesunde anstecken können. 

Am Anfangsbereich der Epidemie ist dieser Unterschied nicht sichtbar, da durch die rein exponentielle Zunahme die "GesamtAktuellInfiziertenBerechnet" fast gleich groß waren wie die "GesamtInfizierteBerechnet". Erst mit Wirksamkeit der Massnahmen wird der Unterschied deutlich. 
Der Fehler wird erst deutlich, wenn durch Massnahmen die Zahl der Neuinktionen deutlich verringert werden.

**Comment by thomasgneiting** [comment]
Der Code wurde durch US und TG angepasst. Die Berechnung der Neu-Infizierten  erfolgt nun durch GesamtAktuellInfizierteBerechnet^RTreduziert.
Die Daten passen nun auch wieder besser mit Aktualisierungen von RKI zusammen. 
Allerdings ergibt sich das Problem, dass die Extraktion der Startwerte N0 und Rt nicht mehr exakt stimmt, da es sich nicht mehr um eine einfache Gleichung GesInfBer = N0^(Rt*tage) handelt. 

Vielmehr geht es nun mit der etwas komplexeren Gleichung für einen Tag i: 

GesamtInfiziertBerechnet[i]=GesamtInfiziertBerechnet[i-1] + GesamtAktuellInfizierteBerechnet[i-1]^Rtreduziert

GesamtAktuellInfizierteBerechnet[i-1]=summe(k=i-1 ... i-1-ta)(GesamtNeuInfizierte[k])

Daher stimmt die einfache lineare Regression nicht mehr. Zum Ausgleich wurde ein Faktor 1.025 eingefügt. Das ist aber nicht die richtige Lösung!

**Comment by thomasgneiting** [comment]
hier noch die Ergebnisse für D:

Aktuell implementierte Version mit GesamtInfiziertBerechnet^Rt: stetiger Anstieg
![grafik](https://user-images.githubusercontent.com/62795691/78424328-1c81c180-766d-11ea-8e7f-84ff4fe8cb07.png)

Test Version mit GesamtAktuellInfiziertBerechnet^Rt: Leichter Rückgang möglich
![grafik](https://user-images.githubusercontent.com/62795691/78424308-f9571200-766c-11ea-9f7d-492aff842885.png)

Wie entwickeln sich Zahlen von RKI?

**Comment by Fabian79FFM** [comment]
Die Testversion gefällt mir besser. Insbesondere bei einer starken Reduzierung von Rt wirkt das für mich plausibler. Ich habe mir auch einmal Gedanken über die Lineare Approximation gemacht. Wenn man sich das neue Modell (Rt bezieht sich nur auf Ansteckende) auf einer logarithmischen Skala anschaut, sieht es so aus: 
![Rplot](https://user-images.githubusercontent.com/62776846/78464640-13840500-76ec-11ea-9695-190869617351.png)
Wir haben also einen leichten Shift nach unten ab der Zeit, ab der Menschen nach der Ansteckung nicht mehr Infektiös sind. Um diese Kurve am besten zu parametrisieren, kann man einen Trick anwenden: Man verschiebt einfach die Punkte um diesen Shift, danach wendet man eine lineare Approximation an und liest hieraus die Parameter ab. Zum Schluss wendet man die Parameter wieder auf das neue Modell an. Grafisch sieht das so aus:
![Rplot01](https://user-images.githubusercontent.com/62776846/78464718-0582b400-76ed-11ea-8c2a-92f9853e8e17.png)
Die grünen Punkte sind die verschobenen Punkte und die blaue Linie ist das neu kalibrierte Alternativmodell. Auf die vorliegenden Daten passt das Modell insgesammt nicht so gut, da man eher schon über der alten Regressionsgeraden liegt, aber das liegt hier wohl an der Datenauswahl. Der Code ist wie folgt:
``# Lineares Modell: Methode wie bisher
historyDfBund %>% ggplot(aes(MeldeDate, sumAnzahlFallBund)) + geom_point() + scale_y_log10()
historyDfBund$log_faelle <-  log10(historyDfBund$sumAnzahlFallBund)
historyDfBund_zeitraum <- historyDfBund %>% filter(MeldeDate > as.Date("2020-02-15") & MeldeDate < as.Date("2020-03-15"))
modell <- lm(log_faelle ~ MeldeDate, data = historyDfBund_zeitraum)

historyDfBund_zeitraum$lin_proxy <- 0
for (i in 1:length(historyDfBund_zeitraum$MeldeDate)){
  historyDfBund_zeitraum$lin_proxy[i] <- coef(modell)[1]+coef(modell)[2]*as.integer(historyDfBund_zeitraum$MeldeDate[i])
}
historyDfBund_zeitraum %>% ggplot(aes(MeldeDate, log_faelle)) + geom_point() + geom_line(aes(MeldeDate, lin_proxy))
historyDfBund_zeitraum$proxy1 <- 10^historyDfBund_zeitraum$lin_proxy

R <- 10^coef(modell)[2]
N0 <- historyDfBund_zeitraum$proxy1[1]

ta <- 10
# Alternatives Modell: nur Ansteckende werden berücksichtigt
historyDfBund_zeitraum$alternativs_Modell <- historyDfBund_zeitraum$proxy1 
for (i in (ta+1):length(historyDfBund_zeitraum$MeldeDate)){
  historyDfBund_zeitraum$alternativs_Modell[i] <- (R^(i-1) - R^(i-ta-1))*N0
}
historyDfBund_zeitraum$log_alternativs_Modell <- log10(historyDfBund_zeitraum$alternativs_Modell)
historyDfBund_zeitraum %>% ggplot(aes(MeldeDate, log_faelle)) + geom_point() + geom_line(aes(MeldeDate, lin_proxy)) + geom_line(aes(MeldeDate, log_alternativs_Modell, colour = "Alternativmodell"))

# Im Bild sieht man ab ta einen Shift nach unten, den man wie folgt quantifizieren kann

historyDfBund_zeitraum$log_alternativs_Modell - historyDfBund_zeitraum$lin_proxy
c <- as.double(log10(R^ta-1)-ta*log10(R))

# Um weiter mit einer linearen Approximation arbeiten zu können, werden die Punkte verschoben
historyDfBund_zeitraum$daten_fuer_lin_prox <- historyDfBund_zeitraum$log_faelle
for (i in (ta+1):length(historyDfBund_zeitraum$MeldeDate)){
  historyDfBund_zeitraum$daten_fuer_lin_prox[i] <- historyDfBund_zeitraum$daten_fuer_lin_prox[i] - c
}
historyDfBund_zeitraum %>% ggplot(aes(MeldeDate, log_faelle)) + geom_point() + geom_point(aes(MeldeDate, daten_fuer_lin_prox, colour = "Für alternative Kalibierung"))+ geom_line(aes(MeldeDate, lin_proxy)) + geom_line(aes(MeldeDate, log_alternativs_Modell, colour = "Alternativmodell"))

# Damit kann man ein neues Modell kalibrieren, das die verschobenen Punkte am besten trifft
modell_neu <-  lm(daten_fuer_lin_prox ~ MeldeDate, data = historyDfBund_zeitraum)


N0_neu <- coef(modell_neu)[1] + coef(modell_neu)[2]*as.integer(historyDfBund_zeitraum$MeldeDate[1])
N0_neu <- 10^N0_neu
R_neu <- 10^coef(modell_neu)[2]

historyDfBund_zeitraum$Modell_neu <- 0
for (i in 1:length(historyDfBund_zeitraum$MeldeDate)){
  historyDfBund_zeitraum$Modell_neu[i] <- R_neu^(i-1)*N0_neu
}
for (i in (ta+1):length(historyDfBund_zeitraum$MeldeDate)){
  historyDfBund_zeitraum$Modell_neu[i] <- (R_neu^(i-1) - R_neu^(i-ta-1))*N0_neu
}

historyDfBund_zeitraum$log_Modell_neu <- log10(historyDfBund_zeitraum$Modell_neu)
historyDfBund_zeitraum %>% ggplot(aes(MeldeDate, log_faelle)) + geom_point() + geom_point(aes(MeldeDate, daten_fuer_lin_prox, colour = "Für alternative Kalibierung"))+ geom_line(aes(MeldeDate, lin_proxy)) + geom_line(aes(MeldeDate, log_alternativs_Modell, colour = "Alternativmodell")) + geom_line(aes(MeldeDate, log_Modell_neu, colour = "Neues Modell"))
  ``

**Comment by uwesterr** [comment]
# Optimierung for R0 durch rmse(ErfassteInfizierteBerechnet,  SumAnzahl)
Implementierung in commit https://github.com/uwesterr/CoronaPredict/commit/ca513593c370c9c499b81449d04a9cca38533423 
```r
  resultDf<- data.frame()
  dfRoNo <- df %>% mutate( Ygesamt = Einwohner)
  dfRoNoOpt <- dfRoNo
  lmModel <-  lm(log10(SumAnzahl) ~ MeldeDate, data = df)
  index <-  0
  for (i in seq(.9,1.2, by = 0.01)) {
    index <- index + 1
    lmModelLoop <- lmModel
   lmModelLoop[["coefficients"]][["MeldeDate"]] <- lmModel[["coefficients"]][["MeldeDate"]]*i
    R0 <- lmModelLoop[["coefficients"]][["MeldeDate"]]
    n0_erfasst <- lmModelLoop %>% predict(data.frame(MeldeDate =startDate))
  
    dfRoNoOpt$n0_erfasst <- n0_erfasst
    dfRoNoOpt$R0<- 10^R0
    
    dfRechenKern <-  Rechenkern(dfRoNoOpt, input, startDate)
    dfRechenKern <- dfRechenKern %>% filter(Tag >= min(df$MeldeDate) & Tag <= max(df$MeldeDate))
    rms <- sqrt(mean((dfRechenKern$ErfassteInfizierteBerechnet-df$SumAnzahl)^2))
    
    resultDf <- rbind(resultDf, data.frame(R0 = R0, RoLin = 10^R0, n0_erfasst = n0_erfasst, coefficient = i,  rms = rms))

    
  }
  resultDf <- resultDf %>% arrange(rms) %>% head(1)
  n0_erfasst_nom_min_max <- data_frame(n0_erfasst_nom = resultDf$n0_erfasst %>% as.numeric())
  R0_conf_nom_min_max <- data.frame(R0_nom= resultDf$RoLin  %>% as.numeric())

  return(list(dfRoNo, n0_erfasst_nom_min_max, R0_conf_nom_min_max, startDate))
```

**Comment by uwesterr** [comment]
# Varianten um GesamtAktuellInfizierteBerechnet zu berechnen 

entweder über ein zurückrechnen der NeuGesamtInfizierte so das summieren am Anfang weiter in die Vergangenheit möglich ist

```r
    expHist <- seq(start_inf, ende_inf)
    sumRt = sum((tailCalcDf$TaeglichReproduktionsRateRt-1)^expHist)
    basisValue <- StartGesamtAktuellInfizierteBerechnet/sumRt
    
    NeuGesamtInfizierteBerechnetHistoryDf <- data.frame(Tag = seq(startDate- ende_inf, startDate-1, by = 1)) %>% mutate(indexBack = as.numeric(-(Tag - startDate))-1) %>% 
      mutate(NeuGesamtInfizierteBerechnet = basisValue*(StartReduzierteRt-1)^(indexBack))

    NeuGesamtInfizierteBerechnetDf <-  rbind(NeuGesamtInfizierteBerechnetHistoryDf %>%  select(Tag, NeuGesamtInfizierteBerechnet ), calcDf %>% select(Tag, NeuGesamtInfizierteBerechnet ))
    
    
  updatecalcDf$GesamtAktuellInfizierteBerechnet <- NeuGesamtInfizierteBerechnetDf %>% filter((Tag < updatecalcDf$Tag - ti) & (Tag >= updatecalcDf$Tag - ende_inf )) %>% 
    summarise(sum = sum(NeuGesamtInfizierteBerechnet)) %>% as.numeric()
```

![resultWithDfApproach](https://user-images.githubusercontent.com/20616185/78499109-077d5f00-774f-11ea-8591-0f6948c4aaa0.png)

oder einen festen wert für die Vergangenheit annehmen solange nicht genügend Datenpunkte verfügbar sind

  ```r
  if (nrow(calcDf) < ende_inf){
      NeuGesamtInfizierteBerechnetHistory = updatecalcDf$RestanteilStartwert*faktor_n_inf
    } else {
      NeuGesamtInfizierteBerechnetHistory = 0
    } 
    
    # TG: Ansatz die gesamt neu infizierten aus den GesamtAktuellInfizierten zu berechnen. Siehe hierzu auch geaenderte Funktion 
    
    # browser()  
    updatecalcDf$GesamtAktuellInfizierteBerechnet <-  NeuGesamtInfizierteBerechnetHistory +
      rollapply(calcDf$NeuGesamtInfizierteBerechnet, ende_inf, sum,
                align = "right", partial =TRUE) %>% tail(1)
```
![resultWithFixedData](https://user-images.githubusercontent.com/20616185/78499174-7064d700-774f-11ea-86f9-c795c8b33c8d.png)

the comparison shows that the second approach is better

**Comment by uwesterr** [comment]
Änderung der Optimierungsschleife mit abbruchskriterium

 ```r
 rmsValue =1e7
  for (i in seq(1.2,0.9, by = -0.01)) {
    index <- index + 1
    lmModelLoop <- lmModel
    lmModelLoop[["coefficients"]][["MeldeDate"]] <- lmModel[["coefficients"]][["MeldeDate"]]*i
    R0 <- lmModelLoop[["coefficients"]][["MeldeDate"]]
    n0_erfasst <- lmModelLoop %>% predict(data.frame(MeldeDate =startDate))
    
    dfRoNoOpt$n0_erfasst <- n0_erfasst
    dfRoNoOpt$R0<- 10^R0
    
    dfRechenKern <-  Rechenkern(dfRoNoOpt, input, startDate)
    dfRechenKern <- dfRechenKern %>% filter(Tag  %in% df$MeldeDate)
    rms <- sqrt(mean((dfRechenKern$ErfassteInfizierteBerechnet-df$SumAnzahl)^2))

    resultDf <- rbind(resultDf, data.frame(R0 = R0, RoLin = 10^R0, n0_erfasst = n0_erfasst, coefficient = i,  rms = rms))
    if (rms< rmsValue) {
      rmsValue <- rms
    } else {
      break
    }
    
  }
``` 
beispiel der optimierung für Deutschland

**Comment by thomasgneiting** [comment]
Hier wurde ein primitiver Anpass-Algorithmus eingeführt: 

[https://github.com/uwesterr/CoronaPredict/tree/bechnung_von_GesamtAktuellInfizierteBerechnet](url)

Ich würde ihn durch einen Levenberg-Marquardt Optimierer ersetzen, wie er z.b. in minpack.lm vorhanden ist. Bei der Modellierung von Halbleitern (Vergleich hier: Dioden) bringt dieser für so eine Aufgabe: 2 Parameter an halbwegs lineare Funktion anpassen, die besten und schnellsten Ergebnisse.

**Comment by thomasgneiting** [comment]
Hier ist die Anpassungsroutine: 

# lousy trick to improve fit, which is not good due to the discrepancy between the assumed function (no^rt*tage) and the real 
# implemented complex function. Should be replaced by a real optimizer. 
# with e.g. a simple levenberg-marquardt optimizer, it should be possible to get a better representation in a reasonable amount of time as the 
# start parameters are already quit good. 

for (i in seq(1.0,1.2, by = 0.02)) {
  for (k in seq(0.9,1.1, by = 0.1)) {

    R0=R0_start*i
    dfRoNoOpt$R0<- 10^(R0)
    
    n0_erfasst <- n0_erfasst_start*k
    dfRoNoOpt$n0_erfasst <- n0_erfasst
    
    #browser()
  
    dfRechenKern <-  isolate(Rechenkern(dfRoNoOpt, input, startDate))
    dfRechenKern <- dfRechenKern %>% filter(Tag  %in% df$MeldeDate)
    rms <- sqrt(mean((dfRechenKern$ErfassteInfizierteBerechnet-df$SumAnzahl)^2))
  
    resultDf <- rbind(resultDf, data.frame(R0 = R0, RoLin = 10^R0, n0_erfasst = n0_erfasst, coefficient = i,  rms = rms))
  }
}
#browser()
resultDf <- resultDf %>% arrange(rms) %>% head(1)
n0_erfasst_nom_min_max <- data_frame(n0_erfasst_nom = resultDf$n0_erfasst %>% as.numeric())
R0_conf_nom_min_max <- data.frame(R0_nom= resultDf$RoLin  %>% as.numeric())
#browser()

**Comment by uwesterr** [comment]
> Hier ist die Anpassungsroutine:
> 
> ```r
> # lousy trick to improve fit, which is not good due to the discrepancy between the assumed function (no^rt*tage) and the real 
> # implemented complex function. Should be replaced by a real optimizer. 
> # with e.g. a simple levenberg-marquardt optimizer, it should be possible to get a better representation in a reasonable amount of time as the 
> # start parameters are already quit good. 
> 
> for (i in seq(1.0,1.2, by = 0.02)) {
>   for (k in seq(0.9,1.1, by = 0.1)) {
> 
>     R0=R0_start*i
>     dfRoNoOpt$R0<- 10^(R0)
>     
>     n0_erfasst <- n0_erfasst_start*k
>     dfRoNoOpt$n0_erfasst <- n0_erfasst
>     
>     #browser()
>   
>     dfRechenKern <-  isolate(Rechenkern(dfRoNoOpt, input, startDate))
>     dfRechenKern <- dfRechenKern %>% filter(Tag  %in% df$MeldeDate)
>     rms <- sqrt(mean((dfRechenKern$ErfassteInfizierteBerechnet-df$SumAnzahl)^2))
>   
>     resultDf <- rbind(resultDf, data.frame(R0 = R0, RoLin = 10^R0, n0_erfasst = n0_erfasst, coefficient = i,  rms = rms))
>   }
> }
> #browser()
> resultDf <- resultDf %>% arrange(rms) %>% head(1)
> n0_erfasst_nom_min_max <- data_frame(n0_erfasst_nom = resultDf$n0_erfasst %>% as.numeric())
> R0_conf_nom_min_max <- data.frame(R0_nom= resultDf$RoLin  %>% as.numeric())
> #browser()
> ```

mit der Optimierung erhalten wir für Deutschland

![OptimizerThomasDeutschland](https://user-images.githubusercontent.com/20616185/78660394-46d1ba00-78cd-11ea-92d2-3127d7b84d26.png)

**Comment by uwesterr** [comment]
replace loop with genetic algorithm optimiser
